jobs:
  create-release:
    env:
      BUMP_ON_BRANCH: ${{ github.event.inputs.bumpBranch }}
      BUMP_TYPE: ${{ github.event.inputs.bumpType }}
    if: github.repository == 'projectnessie/nessie'
    name: Bump version
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        ref: ${{ env.BUMP_ON_BRANCH }}
    - continue-on-error: true
      name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
    - continue-on-error: true
      name: Get previous version information
      run: echo "PREVIOUS_VERSION=$(cat version.txt)" >> ${GITHUB_ENV}
    - continue-on-error: true
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT: java-17
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: nessie-ci
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ci
      name: Bump to version
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: :bumpVersion --bumpType ${{ env.BUMP_TYPE }}
        cache-read-only: true
    - continue-on-error: true
      name: Get bumped version information
      run: 'echo "BUMPED_VERSION=$(cat version.txt)" >> ${GITHUB_ENV}

        echo "BUMPED_VERSION_NO_SNAPSHOT=${BUMPED_VERSION%-SNAPSHOT}" >> ${GITHUB_ENV}

        '
    - continue-on-error: true
      name: Bump versions for Python, site/, helm and UI
      uses: ./.github/actions/bump-versions
      with:
        new-version: ${{ env.BUMPED_VERSION_NO_SNAPSHOT }}
    - continue-on-error: true
      name: Configure bump-version-bot-user in git config
      run: 'git config --global user.email "nessie-bump-version-workflow-noreply@projectnessie.org"

        git config --global user.name "Nessie Bump Version Workflow [bot]"

        '
    - continue-on-error: true
      name: Record next development version in git
      run: git commit -a -m "[bump-version] bump to ${BUMPED_VERSION}"
    - continue-on-error: true
      name: Version information
      run: 'cat <<! >> $GITHUB_STEP_SUMMARY

        ## Version information


        | **Previous Nessie version** | ${PREVIOUS_VERSION}       |

        | **Current Nessie version**  | ${BUMPED_VERSION}         |

        | **Bump type**               | ${BUMP_TYPE}              |

        | Git HEAD                    | \`$(git rev-parse HEAD)\` |

        !

        '
    - continue-on-error: true
      name: Push Git commit
      run: '# Push directly using the remote repo URL, which includes the secret so
        this job can push to the repo

        UPSTREAM="https://${{ secrets.NESSIE_BUILDER }}@github.com/${GITHUB_REPOSITORY}.git"


        # Move the default auth settings in ~/.gitconfig out of the way, so the git-push
        can use the token

        git config --rename-section http.https://github.com/ http.https://save.github.com/


        git push --no-verify "${UPSTREAM}" HEAD:${GITHUB_REF}


        # Move the default auth settings in ~/.gitconfig back

        git config --rename-section http.https://save.github.com/ http.https://github.com/

        '
name: Bump version
on:
  repository_dispatch:
    types: trigger-ga___bump-version.yml
