concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
jobs:
  java:
    env:
      CI_MAC: 'true'
      SPARK_LOCAL_IP: localhost
    if: (github.repository == 'projectnessie/nessie' && github.event_name != 'pull_request')
      || contains(github.event.pull_request.labels.*.name, 'pr-macos-win')
    name: Java/Gradle macOS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
    - continue-on-error: true
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT: java-17
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: nessie-ci
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ci
      name: Gradle / compile
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assemble --scan
        cache-read-only: true
    - continue-on-error: true
      env:
        SPARK_LOCAL_IP: localhost
      name: Gradle / unit test
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: test --scan
    - continue-on-error: true
      if: ${{ failure() }}
      name: Capture Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/build/reports/*

          **/build/test-results/*

          '
        retention-days: 3
    timeout-minutes: 60
name: macOS Build Check
on:
  repository_dispatch:
    types: trigger-ga___ci-mac.yml
