concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
jobs:
  java:
    env:
      SPARK_LOCAL_IP: localhost
    if: (github.repository == 'projectnessie/nessie' && github.event_name != 'pull_request')
      || contains(github.event.pull_request.labels.*.name, 'pr-newer-java')
    name: Exercise Java version
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Setup runner
      uses: ./.github/actions/setup-runner
      with:
        more-memory: 'true'
    - continue-on-error: true
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT: java-17
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: nessie-ci
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ci
      name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
      with:
        cache-read-only: true
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Gradle / compile
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: 'spotlessCheck

          compileAll

          -x :nessie-quarkus:compileAll

          -x :nessie-quarkus-cli:compileAll

          -x :nessie-events-quarkus:compileAll

          --scan

          '
    - continue-on-error: true
      name: Gradle / Compile Quarkus
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: ':nessie-quarkus:compileAll

          :nessie-quarkus-cli:compileAll

          :nessie-events-quarkus:compileAll

          --scan

          '
    - continue-on-error: true
      name: Gradle / unit test
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: test --scan
    - continue-on-error: true
      name: Gradle / check incl. integ-test
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: check --scan
    - continue-on-error: true
      name: Gradle / assemble + publish local
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assemble publishToMavenLocal --scan
    - continue-on-error: true
      name: Gradle / build tools integration tests
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: buildToolsIntegrationTest
    - continue-on-error: true
      if: ${{ failure() }}
      name: Capture Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/build/reports/*

          **/build/test-results/*

          '
        retention-days: 7
    strategy:
      matrix:
        include:
        - java-version: 21
      max-parallel: 1
    timeout-minutes: 90
name: Newer Java versions
on:
  repository_dispatch:
    types: trigger-ga___newer-java.yml
