concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}
jobs:
  java:
    env:
      SPARK_LOCAL_IP: localhost
    if: github.repository == 'projectnessie/nessie'
    name: Publish from main
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Setup runner
      uses: ./.github/actions/setup-runner
    - continue-on-error: true
      name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
    - continue-on-error: true
      name: Gradle / setup
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: projects
        cache-disabled: true
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_ACCESS_ID }}
      name: Gradle / publish snapshot
      run: "# 2 Retries - due to Gradle's old and unfixed CME bug\n./gradlew compileAll\
        \ jar testClasses || \\\n  ./gradlew compileAll jar testClasses || \\\n  ./gradlew\
        \ compileAll jar testClasses \n\n# 2 Retries - to mitigate \"HTTP/502 Bad\
        \ Gateway\" issues\n./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository\
        \ -Prelease -Puber-jar || \\\n  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository\
        \ -Prelease -Puber-jar || \\\n  ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository\
        \ -Prelease -Puber-jar\n"
    - continue-on-error: true
      env:
        ARTIFACTS: ../build-artifacts
      name: Docker images publishing
      run: "rm -rf \"${ARTIFACTS}\"\nmkdir -p \"${ARTIFACTS}\"\n\necho '${{ secrets.GITHUB_TOKEN\
        \ }}' | docker login ghcr.io -u $ --password-stdin \ntools/dockerbuild/build-push-images.sh\
        \ \\\n  -a \"${ARTIFACTS}\" \\\n  -g \":nessie-quarkus\" \\\n  -p \"servers/quarkus-server\"\
        \ \\\n  ghcr.io/projectnessie/nessie-unstable\ntools/dockerbuild/build-push-images.sh\
        \ \\\n  -a \"${ARTIFACTS}\" \\\n  -g \":nessie-gc-tool\" \\\n  -p \"gc/gc-tool\"\
        \ \\\n  -d \"Dockerfile-gctool\" \\\n  ghcr.io/projectnessie/nessie-gc-unstable\n\
        \nrm -rf \"${ARTIFACTS}\"\n"
    timeout-minutes: 60
name: Publish in-development builds from main
on:
  repository_dispatch:
    types: trigger-ga___snapshot-publish.yml
